%% model_export.pl - Domain Model Export Utilities
%
%  Provides predicates for exporting domain models to various formats
%  including Prolog facts, structured terms, and text reports.
%
%  @author Generated for larj-model
%  @version 1.0

:- module(model_export, [
    % Export to Prolog facts file
    export_model_to_file/2,
    export_context_to_file/3,

    % Export to structured terms
    export_model_term/2,
    export_context_term/2,

    % Export to report format
    generate_model_report/2,
    generate_context_report/2,

    % Export to Workflowy format
    export_to_workflowy/2
]).

:- use_module(ddd_schema).
:- use_module(model_builder).

%% --------------------------------------------------------------------------
%% Export to Prolog Facts File
%% --------------------------------------------------------------------------

%% export_model_to_file(+ModelName, +FilePath) is det
%
%  Exports the entire model to a Prolog facts file.
%
%  @param ModelName  Name for the model (used in file header)
%  @param FilePath   Path to write the file
export_model_to_file(ModelName, FilePath) :-
    open(FilePath, write, Stream),
    format(Stream, '%% Domain Model: ~w~n', [ModelName]),
    format(Stream, '%% Generated by larj-model~n', []),
    format(Stream, '%% ~n~n', []),
    format(Stream, ':- module(~w_model, []).~n~n', [ModelName]),
    format(Stream, ':- use_module(ddd_schema).~n~n', []),
    export_all_contexts(Stream),
    export_all_context_relationships(Stream),
    export_all_moment_intervals(Stream),
    export_all_roles(Stream),
    export_all_ppts(Stream),
    export_all_descriptions(Stream),
    export_all_aggregates(Stream),
    export_all_services(Stream),
    export_all_domain_classifications(Stream),
    close(Stream).

%% export_context_to_file(+ContextId, +ModelName, +FilePath) is det
%
%  Exports a single bounded context to a Prolog facts file.
export_context_to_file(ContextId, ModelName, FilePath) :-
    bounded_context(ContextId, _, _),
    open(FilePath, write, Stream),
    format(Stream, '%% Bounded Context: ~w~n', [ContextId]),
    format(Stream, '%% Model: ~w~n', [ModelName]),
    format(Stream, '%% Generated by larj-model~n~n', []),
    export_context_facts(Stream, ContextId),
    close(Stream).

% Internal export helpers
export_all_contexts(Stream) :-
    format(Stream, '%% Bounded Contexts~n', []),
    forall(
        bounded_context(Id, Name, Scope),
        format(Stream, 'bounded_context(~q, ~q, ~q).~n', [Id, Name, Scope])
    ),
    format(Stream, '~n', []),
    format(Stream, '%% Context Terms~n', []),
    forall(
        context_term(ContextId, Term, Meaning),
        format(Stream, 'context_term(~q, ~q, ~q).~n', [ContextId, Term, Meaning])
    ),
    format(Stream, '~n', []).

export_all_context_relationships(Stream) :-
    format(Stream, '%% Context Relationships~n', []),
    forall(
        context_relationship(Up, Down, Pattern, Notes),
        format(Stream, 'context_relationship(~q, ~q, ~q, ~q).~n', [Up, Down, Pattern, Notes])
    ),
    format(Stream, '~n', []).

export_all_moment_intervals(Stream) :-
    format(Stream, '%% Moment-Intervals~n', []),
    forall(
        moment_interval(Id, ContextId),
        (
            format(Stream, 'moment_interval(~q, ~q).~n', [Id, ContextId]),
            export_mi_details(Stream, Id)
        )
    ),
    format(Stream, '~n', []).

export_mi_details(Stream, Id) :-
    forall(mi_temporal_type(Id, Type),
        format(Stream, 'mi_temporal_type(~q, ~q).~n', [Id, Type])),
    forall(mi_attribute(Id, Name, Spec),
        format(Stream, 'mi_attribute(~q, ~q, ~q).~n', [Id, Name, Spec])),
    forall(mi_behaviour(Id, Name, Spec),
        format(Stream, 'mi_behaviour(~q, ~q, ~q).~n', [Id, Name, Spec])),
    forall(mi_detail(Id, DetailId, Spec),
        format(Stream, 'mi_detail(~q, ~q, ~q).~n', [Id, DetailId, Spec])),
    forall(mi_status(Id, StatusName, Spec),
        format(Stream, 'mi_status(~q, ~q, ~q).~n', [Id, StatusName, Spec])),
    forall(mi_plan_actual(Id, ActualId, RelType),
        format(Stream, 'mi_plan_actual(~q, ~q, ~q).~n', [Id, ActualId, RelType])).

export_all_roles(Stream) :-
    format(Stream, '%% Roles~n', []),
    forall(
        role(Id, ContextId),
        (
            format(Stream, 'role(~q, ~q).~n', [Id, ContextId]),
            export_role_details(Stream, Id)
        )
    ),
    format(Stream, '~n', []).

export_role_details(Stream, Id) :-
    forall(role_attribute(Id, Name, Spec),
        format(Stream, 'role_attribute(~q, ~q, ~q).~n', [Id, Name, Spec])),
    forall(role_behaviour(Id, Name, Spec),
        format(Stream, 'role_behaviour(~q, ~q, ~q).~n', [Id, Name, Spec])),
    forall(role_played_by(Id, PPTId),
        format(Stream, 'role_played_by(~q, ~q).~n', [Id, PPTId])),
    forall(role_participates_in(Id, MIId),
        format(Stream, 'role_participates_in(~q, ~q).~n', [Id, MIId])).

export_all_ppts(Stream) :-
    format(Stream, '%% Parties, Places, and Things~n', []),
    forall(
        party_place_thing(Id, ContextId),
        (
            format(Stream, 'party_place_thing(~q, ~q).~n', [Id, ContextId]),
            export_ppt_details(Stream, Id)
        )
    ),
    format(Stream, '~n', []).

export_ppt_details(Stream, Id) :-
    forall(ppt_subtype(Id, Subtype),
        format(Stream, 'ppt_subtype(~q, ~q).~n', [Id, Subtype])),
    forall(ppt_attribute(Id, Name, Spec),
        format(Stream, 'ppt_attribute(~q, ~q, ~q).~n', [Id, Name, Spec])),
    forall(ppt_behaviour(Id, Name, Spec),
        format(Stream, 'ppt_behaviour(~q, ~q, ~q).~n', [Id, Name, Spec])),
    forall(ppt_described_by(Id, DescId),
        format(Stream, 'ppt_described_by(~q, ~q).~n', [Id, DescId])),
    forall(ppt_plays_role(Id, RoleId),
        format(Stream, 'ppt_plays_role(~q, ~q).~n', [Id, RoleId])).

export_all_descriptions(Stream) :-
    format(Stream, '%% Descriptions~n', []),
    forall(
        description(Id, ContextId),
        (
            format(Stream, 'description(~q, ~q).~n', [Id, ContextId]),
            export_desc_details(Stream, Id)
        )
    ),
    format(Stream, '~n', []).

export_desc_details(Stream, Id) :-
    forall(desc_attribute(Id, Name, Spec),
        format(Stream, 'desc_attribute(~q, ~q, ~q).~n', [Id, Name, Spec])),
    forall(desc_behaviour(Id, Name, Spec),
        format(Stream, 'desc_behaviour(~q, ~q, ~q).~n', [Id, Name, Spec])),
    forall(desc_default_value(Id, Name, Value),
        format(Stream, 'desc_default_value(~q, ~q, ~q).~n', [Id, Name, Value])),
    forall(desc_applies_to(Id, PPTType),
        format(Stream, 'desc_applies_to(~q, ~q).~n', [Id, PPTType])).

export_all_aggregates(Stream) :-
    format(Stream, '%% Aggregates~n', []),
    forall(
        aggregate(Id, ContextId),
        (
            format(Stream, 'aggregate(~q, ~q).~n', [Id, ContextId]),
            export_aggregate_details(Stream, Id)
        )
    ),
    format(Stream, '~n', []).

export_aggregate_details(Stream, Id) :-
    forall(aggregate_root(Id, RootId),
        format(Stream, 'aggregate_root(~q, ~q).~n', [Id, RootId])),
    forall(aggregate_member(Id, MemberId),
        format(Stream, 'aggregate_member(~q, ~q).~n', [Id, MemberId])),
    forall(aggregate_invariant(Id, Invariant),
        format(Stream, 'aggregate_invariant(~q, ~q).~n', [Id, Invariant])).

export_all_services(Stream) :-
    format(Stream, '%% Domain Services~n', []),
    forall(
        domain_service(Id, ContextId),
        (
            format(Stream, 'domain_service(~q, ~q).~n', [Id, ContextId]),
            export_service_details(Stream, Id)
        )
    ),
    format(Stream, '~n', []).

export_service_details(Stream, Id) :-
    forall(service_operation(Id, Name, Spec),
        format(Stream, 'service_operation(~q, ~q, ~q).~n', [Id, Name, Spec])),
    forall(service_coordinates(Id, ObjectId),
        format(Stream, 'service_coordinates(~q, ~q).~n', [Id, ObjectId])).

export_all_domain_classifications(Stream) :-
    format(Stream, '%% Domain Classifications~n', []),
    forall(core_domain(Id),
        format(Stream, 'core_domain(~q).~n', [Id])),
    forall(supporting_domain(Id),
        format(Stream, 'supporting_domain(~q).~n', [Id])),
    forall(generic_domain(Id),
        format(Stream, 'generic_domain(~q).~n', [Id])),
    format(Stream, '~n', []).

export_context_facts(Stream, ContextId) :-
    bounded_context(ContextId, Name, Scope),
    format(Stream, 'bounded_context(~q, ~q, ~q).~n~n', [ContextId, Name, Scope]),
    forall(context_term(ContextId, Term, Meaning),
        format(Stream, 'context_term(~q, ~q, ~q).~n', [ContextId, Term, Meaning])),
    format(Stream, '~n', []),
    forall(moment_interval(Id, ContextId), (
        format(Stream, 'moment_interval(~q, ~q).~n', [Id, ContextId]),
        export_mi_details(Stream, Id)
    )),
    forall(role(Id, ContextId), (
        format(Stream, 'role(~q, ~q).~n', [Id, ContextId]),
        export_role_details(Stream, Id)
    )),
    forall(party_place_thing(Id, ContextId), (
        format(Stream, 'party_place_thing(~q, ~q).~n', [Id, ContextId]),
        export_ppt_details(Stream, Id)
    )),
    forall(description(Id, ContextId), (
        format(Stream, 'description(~q, ~q).~n', [Id, ContextId]),
        export_desc_details(Stream, Id)
    )).

%% --------------------------------------------------------------------------
%% Export to Structured Terms
%% --------------------------------------------------------------------------

%% export_model_term(+ModelName, -ModelTerm) is det
%
%  Exports the entire model as a structured Prolog term.
%
%  @param ModelName  Name for the model
%  @param ModelTerm  The structured term representation
export_model_term(ModelName, ModelTerm) :-
    findall(context(Id, Name, Scope, Terms), (
        bounded_context(Id, Name, Scope),
        findall(term(T, M), context_term(Id, T, M), Terms)
    ), Contexts),
    findall(relationship(Up, Down, Pattern, Notes),
        context_relationship(Up, Down, Pattern, Notes), Relationships),
    findall(mi(Id, Context, TempType, Attrs, Behaviours, Details, Statuses),
        export_mi_term(Id, Context, TempType, Attrs, Behaviours, Details, Statuses),
        MomentIntervals),
    findall(role(Id, Context, Player, MIs, Attrs, Behaviours),
        export_role_term(Id, Context, Player, MIs, Attrs, Behaviours),
        Roles),
    findall(ppt(Id, Context, Subtype, DescBy, RolesPlayed, Attrs, Behaviours),
        export_ppt_term(Id, Context, Subtype, DescBy, RolesPlayed, Attrs, Behaviours),
        PPTs),
    findall(desc(Id, Context, AppliesTo, Defaults, Attrs, Behaviours),
        export_desc_term(Id, Context, AppliesTo, Defaults, Attrs, Behaviours),
        Descriptions),
    findall(agg(Id, Context, Root, Members, Invariants),
        export_aggregate_term(Id, Context, Root, Members, Invariants),
        Aggregates),
    findall(svc(Id, Context, Operations, Coordinates),
        export_service_term(Id, Context, Operations, Coordinates),
        Services),
    ModelTerm = model(
        ModelName,
        contexts(Contexts),
        context_map(Relationships),
        moment_intervals(MomentIntervals),
        roles(Roles),
        parties_places_things(PPTs),
        descriptions(Descriptions),
        aggregates(Aggregates),
        services(Services)
    ).

export_mi_term(Id, Context, TempType, Attrs, Behaviours, Details, Statuses) :-
    moment_interval(Id, Context),
    (mi_temporal_type(Id, TempType) -> true ; TempType = unknown),
    findall(attr(N, S), mi_attribute(Id, N, S), Attrs),
    findall(beh(N, S), mi_behaviour(Id, N, S), Behaviours),
    findall(detail(DId, S), mi_detail(Id, DId, S), Details),
    findall(status(SN, S), mi_status(Id, SN, S), Statuses).

export_role_term(Id, Context, Player, MIs, Attrs, Behaviours) :-
    role(Id, Context),
    findall(P, role_played_by(Id, P), Players),
    (Players = [Player|_] -> true ; Player = none),
    findall(MI, role_participates_in(Id, MI), MIs),
    findall(attr(N, S), role_attribute(Id, N, S), Attrs),
    findall(beh(N, S), role_behaviour(Id, N, S), Behaviours).

export_ppt_term(Id, Context, Subtype, DescBy, RolesPlayed, Attrs, Behaviours) :-
    party_place_thing(Id, Context),
    (ppt_subtype(Id, Subtype) -> true ; Subtype = unknown),
    findall(D, ppt_described_by(Id, D), DescByList),
    (DescByList = [DescBy|_] -> true ; DescBy = none),
    findall(R, ppt_plays_role(Id, R), RolesPlayed),
    findall(attr(N, S), ppt_attribute(Id, N, S), Attrs),
    findall(beh(N, S), ppt_behaviour(Id, N, S), Behaviours).

export_desc_term(Id, Context, AppliesTo, Defaults, Attrs, Behaviours) :-
    description(Id, Context),
    findall(T, desc_applies_to(Id, T), AppliesToList),
    (AppliesToList = [AppliesTo|_] -> true ; AppliesTo = unknown),
    findall(default(N, V), desc_default_value(Id, N, V), Defaults),
    findall(attr(N, S), desc_attribute(Id, N, S), Attrs),
    findall(beh(N, S), desc_behaviour(Id, N, S), Behaviours).

export_aggregate_term(Id, Context, Root, Members, Invariants) :-
    aggregate(Id, Context),
    (aggregate_root(Id, Root) -> true ; Root = none),
    findall(M, aggregate_member(Id, M), Members),
    findall(I, aggregate_invariant(Id, I), Invariants).

export_service_term(Id, Context, Operations, Coordinates) :-
    domain_service(Id, Context),
    findall(op(N, S), service_operation(Id, N, S), Operations),
    findall(O, service_coordinates(Id, O), Coordinates).

%% export_context_term(+ContextId, -ContextTerm) is det
%
%  Exports a single bounded context as a structured term.
export_context_term(ContextId, ContextTerm) :-
    bounded_context(ContextId, Name, Scope),
    findall(term(T, M), context_term(ContextId, T, M), Terms),
    findall(mi(Id, TT, A, B, D, S),
        (moment_interval(Id, ContextId),
         export_mi_term(Id, ContextId, TT, A, B, D, S)),
        MIs),
    findall(role(Id, P, MIList, A, B),
        (role(Id, ContextId),
         export_role_term(Id, ContextId, P, MIList, A, B)),
        Roles),
    findall(ppt(Id, ST, DB, RP, A, B),
        (party_place_thing(Id, ContextId),
         export_ppt_term(Id, ContextId, ST, DB, RP, A, B)),
        PPTs),
    findall(desc(Id, AT, Def, A, B),
        (description(Id, ContextId),
         export_desc_term(Id, ContextId, AT, Def, A, B)),
        Descs),
    ContextTerm = context(
        ContextId,
        Name,
        Scope,
        terms(Terms),
        moment_intervals(MIs),
        roles(Roles),
        parties_places_things(PPTs),
        descriptions(Descs)
    ).

%% --------------------------------------------------------------------------
%% Export to Report Format
%% --------------------------------------------------------------------------

%% generate_model_report(+ModelName, -Report) is det
%
%  Generates a human-readable text report of the model.
generate_model_report(ModelName, Report) :-
    format(atom(Header), '# Domain Model: ~w~n~n', [ModelName]),
    generate_contexts_report(ContextsReport),
    generate_context_map_report(MapReport),
    generate_objects_report(ObjectsReport),
    generate_aggregates_report(AggsReport),
    atomic_list_concat([Header, ContextsReport, MapReport, ObjectsReport, AggsReport], Report).

generate_contexts_report(Report) :-
    findall(ContextText, (
        bounded_context(Id, Name, Scope),
        format(atom(ContextText), '## Bounded Context: ~w~n- Name: ~w~n- Scope: ~w~n~n', [Id, Name, Scope])
    ), ContextTexts),
    atomic_list_concat(ContextTexts, Report).

generate_context_map_report(Report) :-
    findall(RelText, (
        context_relationship(Up, Down, Pattern, Notes),
        format(atom(RelText), '- ~w -> ~w (~w): ~w~n', [Up, Down, Pattern, Notes])
    ), RelTexts),
    (RelTexts = [] ->
        Report = ''
    ;
        atomic_list_concat(['## Context Map~n' | RelTexts], Report)
    ).

generate_objects_report(Report) :-
    format(atom(MIHeader), '~n## Moment-Intervals (Pink)~n', []),
    findall(MIText, (
        moment_interval(Id, Context),
        (mi_temporal_type(Id, TT) -> true ; TT = unknown),
        format(atom(MIText), '- ~w (~w) in ~w~n', [Id, TT, Context])
    ), MITexts),
    format(atom(RoleHeader), '~n## Roles (Yellow)~n', []),
    findall(RoleText, (
        role(Id, Context),
        format(atom(RoleText), '- ~w in ~w~n', [Id, Context])
    ), RoleTexts),
    format(atom(PPTHeader), '~n## Parties/Places/Things (Green)~n', []),
    findall(PPTText, (
        party_place_thing(Id, Context),
        (ppt_subtype(Id, ST) -> true ; ST = unknown),
        format(atom(PPTText), '- ~w (~w) in ~w~n', [Id, ST, Context])
    ), PPTTexts),
    format(atom(DescHeader), '~n## Descriptions (Blue)~n', []),
    findall(DescText, (
        description(Id, Context),
        format(atom(DescText), '- ~w in ~w~n', [Id, Context])
    ), DescTexts),
    atomic_list_concat([MIHeader | MITexts], MIReport),
    atomic_list_concat([RoleHeader | RoleTexts], RoleReport),
    atomic_list_concat([PPTHeader | PPTTexts], PPTReport),
    atomic_list_concat([DescHeader | DescTexts], DescReport),
    atomic_list_concat([MIReport, RoleReport, PPTReport, DescReport], Report).

generate_aggregates_report(Report) :-
    format(atom(Header), '~n## Aggregates~n', []),
    findall(AggText, (
        aggregate(Id, Context),
        (aggregate_root(Id, Root) -> true ; Root = none),
        format(atom(AggText), '- ~w (root: ~w) in ~w~n', [Id, Root, Context])
    ), AggTexts),
    atomic_list_concat([Header | AggTexts], Report).

%% generate_context_report(+ContextId, -Report) is det
%
%  Generates a report for a single bounded context.
generate_context_report(ContextId, Report) :-
    bounded_context(ContextId, Name, Scope),
    format(atom(Header), '# Bounded Context: ~w~n- Name: ~w~n- Scope: ~w~n~n', [ContextId, Name, Scope]),
    findall(MIText, (
        moment_interval(Id, ContextId),
        format(atom(MIText), '  - ~w~n', [Id])
    ), MITexts),
    findall(RoleText, (
        role(Id, ContextId),
        format(atom(RoleText), '  - ~w~n', [Id])
    ), RoleTexts),
    findall(PPTText, (
        party_place_thing(Id, ContextId),
        format(atom(PPTText), '  - ~w~n', [Id])
    ), PPTTexts),
    findall(DescText, (
        description(Id, ContextId),
        format(atom(DescText), '  - ~w~n', [Id])
    ), DescTexts),
    atomic_list_concat(['## Moment-Intervals~n' | MITexts], MISection),
    atomic_list_concat(['## Roles~n' | RoleTexts], RoleSection),
    atomic_list_concat(['## Parties/Places/Things~n' | PPTTexts], PPTSection),
    atomic_list_concat(['## Descriptions~n' | DescTexts], DescSection),
    atomic_list_concat([Header, MISection, RoleSection, PPTSection, DescSection], Report).

%% --------------------------------------------------------------------------
%% Export to Workflowy Format
%% --------------------------------------------------------------------------

%% export_to_workflowy(+ModelName, -WorkflowyText) is det
%
%  Exports the model in Workflowy-compatible indented format.
export_to_workflowy(ModelName, WorkflowyText) :-
    format(atom(Header), '- Domain Model: ~w~n', [ModelName]),
    export_contexts_workflowy(ContextsText),
    export_objects_workflowy(ObjectsText),
    export_aggregates_workflowy(AggsText),
    atomic_list_concat([Header, ContextsText, ObjectsText, AggsText], WorkflowyText).

export_contexts_workflowy(Text) :-
    findall(ContextText, (
        bounded_context(Id, Name, Scope),
        findall(TermText, (
            context_term(Id, Term, Meaning),
            format(atom(TermText), '      - ~w: ~w~n', [Term, Meaning])
        ), TermTexts),
        atomic_list_concat(TermTexts, TermsText),
        format(atom(ContextText), '  - Bounded Context: ~w~n    - Name: ~w~n    - Scope: ~w~n    - Terms~n~w', [Id, Name, Scope, TermsText])
    ), ContextTexts),
    atomic_list_concat(ContextTexts, Text).

export_objects_workflowy(Text) :-
    findall(MIText, (
        moment_interval(Id, Context),
        (mi_temporal_type(Id, TT) -> true ; TT = unknown),
        format(atom(MIText), '    - ~w (~w) [~w]~n', [Id, TT, Context])
    ), MITexts),
    findall(RoleText, (
        role(Id, Context),
        format(atom(RoleText), '    - ~w [~w]~n', [Id, Context])
    ), RoleTexts),
    findall(PPTText, (
        party_place_thing(Id, Context),
        (ppt_subtype(Id, ST) -> true ; ST = unknown),
        format(atom(PPTText), '    - ~w (~w) [~w]~n', [Id, ST, Context])
    ), PPTTexts),
    findall(DescText, (
        description(Id, Context),
        format(atom(DescText), '    - ~w [~w]~n', [Id, Context])
    ), DescTexts),
    atomic_list_concat(['  - Moment-Intervals (Pink)~n' | MITexts], MISection),
    atomic_list_concat(['  - Roles (Yellow)~n' | RoleTexts], RoleSection),
    atomic_list_concat(['  - Parties/Places/Things (Green)~n' | PPTTexts], PPTSection),
    atomic_list_concat(['  - Descriptions (Blue)~n' | DescTexts], DescSection),
    atomic_list_concat([MISection, RoleSection, PPTSection, DescSection], Text).

export_aggregates_workflowy(Text) :-
    findall(AggText, (
        aggregate(Id, Context),
        (aggregate_root(Id, Root) -> true ; Root = none),
        findall(MemberText, (
            aggregate_member(Id, Member),
            format(atom(MemberText), '      - ~w~n', [Member])
        ), MemberTexts),
        atomic_list_concat(MemberTexts, MembersText),
        format(atom(AggText), '    - ~w~n      - Root: ~w~n      - Context: ~w~n      - Members~n~w', [Id, Root, Context, MembersText])
    ), AggTexts),
    atomic_list_concat(['  - Aggregates~n' | AggTexts], Text).
